MoodBite/MoodBite/Models/RecipeViewModel/RecipeDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MoodBite.Models.RecipeViewModel
{
    public class RecipeDetailViewModel
    {
        public IEnumerable<vw_RecipeDetailsWithoutIngredients> recipeDetailsWithoutIngredients;
        public IEnumerable<vw_RecommendedRecipeForMood> recommendedRecipes;
        public Dictionary<string, List<string>> recipeIngredients;
        public IEnumerable<vw_CoverImageOfRecipes> imagesOfRecipe;
        public vw_CoverImageOfRecipes recipeImagesReadMore;
        public vw_RecommendedRecipeForMood recipeReadMore;
        public IEnumerable<RecipeIngredient> recipeIngredientsReadMore;
        public vw_RecipeDetailsWithoutIngredients recipeDetailsWithoutIngredientsReadMore;
        public IEnumerable<vw_RecipeDetailsWithoutIngredientsWithRating> recipeDetailsWithRating;
        public IEnumerable<vw_recipeUploadersNameWithRating> recipeUploadersNameWithRatingReadMore;
        public IEnumerable<vw_UsersUploadCounts> userUploadCounts;
        public vw_AllUserColWithRecipeID uploadersProfilePic;
        public IEnumerable<vw_AllRecipeDetailsWithFoodCategoryName> allRecipeWithFoodCategoryName;
        public IEnumerable<string> allergy;
        public IEnumerable<string> foodCategories;
        public IEnumerable<string> intolerance;
        public UserPremium userPremium;
        public vw_FoodSaleView foodSaleView;
        public IEnumerable<int> faveRecipes;
        public vw_RecipeReadMoreStocksView recipeStocksView;
        public List<vw_IncomingOrderView> incomingOrderView;
        public List<vw_MyFavoritesView> myFavoritesView;
    }
}

MoodBite/MoodBite/Models/UploadRecipeModel/UploadRecipe.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MoodBite.Models.UploadRecipeModel
{
    public class UploadRecipe
    {
        public Recipe recipe;
        public UserPremium userPremium;
    }
}

MoodBite/MoodBite/Controllers/UsersPageController.cs
using System;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Rotativa;
using MoodBite.Models.RecipeViewModel;
using System.Net.Http.Headers;
using System.Collections.Generic;
using MoodBite.Models.FoodSaleModel;
using System.Globalization;
using System.Reflection;
using MoodBite.Contract;
using System.Text.RegularExpressions;

namespace MoodBite.Controllers
{
    [HandleError]
    [Authorize(Roles = "User, Admin")]
    [OutputCache(NoStore = true, Duration = 0)]
    public class UsersPageController : BaseController
    {
        public string localChosenMood;
        //modal pop up which prompts the user to select a mood
        
        public ActionResult ChooseMood()
        {
            if(User.Identity.IsAuthenticated)
            {
                var moodList = _db.Mood.ToList();
                return View(moodList);
            }
            return RedirectToAction("../Account/LogOut");
        }

        //handles the submission for mood selection
        [HttpPost]
        public ActionResult ChooseMood(string chosenMood)
        {
            if (User.Identity.IsAuthenticated)
            {
                Session["ChosenMood"] = chosenMood;
                this.localChosenMood = chosenMood;
                //return RedirectToAction("UsersHome");
                return RedirectToAction("UsersHome");
            } else
            {
                return RedirectToAction("../Account/LogOut");
            }
        }

        //after selecting mood user will be redirected here, where recipes will be generated based on mood inputted
        public ActionResult UsersHome()
        {
            if (User.Identity.IsAuthenticated && Session["ChosenMood"] != null)
            {
                var chosenMood = Session["ChosenMood"].ToString();
                var recipedetail = RecipeDetail(chosenMood);
                Session["SearchInput"] = string.Empty;
                if (TempData["recipedetail"] == null)
                {
                    return View(recipedetail);
                } else
                {
                    var tempRecipeDetail = TempData["recipedetail"] as RecipeDetailViewModel;
                    return View(tempRecipeDetail);
                }
            }
            else if (User.Identity.IsAuthenticated && Session["ChosenMood"] == null)
            {
                return RedirectToAction("ChooseMood");
            }
            {
                return RedirectToAction("../Account/LogOut");
            }
        }

        [HttpPost]
        public ActionResult UsersHome(string search, string[] allergyInp, string[] intoleranceInp, string[] foodCategoryInp)
        {
            if (User.Identity.IsAuthenticated && Session["ChosenMood"] != null)
            {
                if(string.IsNullOrWhiteSpace(search))
                {
                    var chosenMood = Session["ChosenMood"] as String;
                    var user = Session["User"] as User;
                    var recipedetail = RecipeDetail(chosenMood);
                    TempData["recipedetail"] = recipedetail;
                    Session["SearchInput"] = search;
                    return Json(new { success = true});
                } else
                {
                    var chosenMood = Session["ChosenMood"] as String;
                    var user = Session["User"] as User;
                    var recipedetail = RecipeDetail(chosenMood, search, allergyInp, intoleranceInp, foodCategoryInp);
                    TempData["recipedetail"] = recipedetail;
                    Session["SearchInput"] = search;
                    return Json(new { success = true });
                }
            }
            else
            {
                return Json(new { success = false, msg = "Session timeout."});
            }
        }

        //view full details when read more button is clicked from the recipe card/item
        public ActionResult RecipeReadMore(int id)
        {
            if (!string.IsNullOrEmpty(Session["returnurl"] as string))
            {
                var returnurl = Session["returnurl"] as string;
                returnurl = returnurl.Replace("/UsersPage/RecipeReadMore/", "");
                var recipeDetail = ReadMore(id);
                var user = Session["User"] as User;
                if (recipeDetail == null)
                {
                    return RedirectToAction("../Error/PageNotFound");
                }
                return View(recipeDetail);
            }
            if (Session["ChosenMood"] == null || Session["User"] == null)
            {
                return RedirectToAction("../Account/LogOut");
            }
            else if(User.Identity.IsAuthenticated && Session["ChosenMood"] != null && Session["User"] != null)
            {
                var recipeDetail = ReadMore(id);
                var user = Session["User"] as User;
                if (recipeDetail == null)
                {
                    return RedirectToAction("../Error/PageNotFound");
                }
                return View(recipeDetail);
            }
            else
            {
                return RedirectToAction("../Home/Index");
            }
        }

        [HttpPost]
        public ActionResult RecipeReadMore(int recipeID, int userID)
        {
            return Json(new { success = true, message = "Product has been added to your shopping cart." });
        }

        public ActionResult UploadRecipe()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = _db.User.Where(m => m.Username == User.Identity.Name).FirstOrDefault();
                var model = new Recipe();
                var userPremium = _db.UserPremium.Where(m => m.UserID == user.userID).FirstOrDefault();
                var foodCategory = _db.FoodCategory.ToList();
                Session["UserPremium"] = userPremium;
                Session["FoodCategory"] = foodCategory;
                return View(model);
            }
            else
            {
                return RedirectToAction("../Account/LogOuts");
            }
           
        }

        [HttpPost]
        public ActionResult UploadRecipe(Recipe recipe, string foodcategory, string ingcount, string moodid, string[] ingredientName, double[] ingredientQty, string[] ingredientUnit, double? price, string shippedfrom, string stock, string forSale)
        {
            string[] allowedExtensions = { ".jpg", ".jpeg", ".png", ".bmp", ".webp", ".svg" };
            var imageFile = Request.Files.Get("imageFile");
            string fileExtension = Path.GetExtension(imageFile.FileName).ToLower();
            TimeSpan preparationTime;
            TimeSpan cookingDuration;

            if (string.IsNullOrEmpty(recipe.RecipeName))
            {
                return Json(new { success = false, msg = "Please fill in the recipe name."});
            }

            if (string.IsNullOrEmpty(recipe.RecipeDescription))
            {
                return Json(new { success = false, msg = "Please fill in the recipe description." });
            }

            if (string.IsNullOrEmpty(Convert.ToString(recipe.PreparationTime)))
            {
                return Json(new { success = false, msg = "Please fill in the preparation time." });
            }

            string timePattern = @"^(?<hours>\d{2}):(?<minutes>\d{2}):(?<seconds>\d{2})$";
            Match preparationTimeMatch = Regex.Match(recipe.PreparationTime.ToString(), timePattern);
            if (!preparationTimeMatch.Success)
            {
                return Json(new { success = false, msg = "Invalid preparation time format. Expected format: hh:mm:ss" });
            }

            int preparationHours = int.Parse(preparationTimeMatch.Groups["hours"].Value);
            int preparationMinutes = int.Parse(preparationTimeMatch.Groups["minutes"].Value);
            int preparationSeconds = int.Parse(preparationTimeMatch.Groups["seconds"].Value);

            if (preparationHours < 0 || preparationHours > 23 || preparationMinutes < 0 || preparationMinutes > 59 || preparationSeconds < 0 || preparationSeconds > 59)
            {
                return Json(new { success = false, msg = "Invalid preparation time. Please enter a valid time." });
            }

            preparationTime = new TimeSpan(preparationHours, preparationMinutes, preparationSeconds);
            if (preparationTime.TotalMinutes < 1)
            {
                return Json(new { success = false, msg = "Preparation time should be at least 1 minute." });
            }

            if (string.IsNullOrEmpty(Convert.ToString(recipe.CookingDuration)))
            {
                return Json(new { success = false, msg = "Please fill in the cooking duration." });
            }

            Match cookingDurationMatch = Regex.Match(recipe.CookingDuration.ToString(), timePattern);
            if (!cookingDurationMatch.Success)
            {
                return Json(new { success = false, msg = "Invalid cooking duration time format. Expected format: hh:mm:ss" });
            }

            int cookingHours = int.Parse(cookingDurationMatch.Groups["hours"].Value);
            int cookingMinutes = int.Parse(cookingDurationMatch.Groups["minutes"].Value);
            int cookingSeconds = int.Parse(cookingDurationMatch.Groups["seconds"].Value);

            if (cookingHours < 0 || cookingHours > 23 || cookingMinutes < 0 || cookingMinutes > 59 || cookingSeconds < 0 || cookingSeconds > 59)
            {
                return Json(new { success = false, msg = "Invalid cooking duration. Please enter a valid time." });
            }

            cookingDuration = new TimeSpan(cookingHours, cookingMinutes, cookingSeconds);
            if (cookingDuration.TotalMinutes < 1)
            {
                return Json(new { success = false, msg = "Cooking duration should be at least 1 minute." });
            }

MoodBite/MoodBite/Views/UsersPage/CheckOutPage.cshtml
@model vw_CheckOutView


@{
    ViewBag.Title = "CheckOutPage";
    Layout = "~/Views/Shared/_StandardLayout.cshtml";
    decimal total = 0;
    var user = Session["User"] as User;

    Random random = new Random();
    int deliveryFee = random.Next(5, 126);
    decimal subTotal = 0;
    int estArrivalTime = random.Next(5, 60);
}

<!-- Favicon -->
<link href="~/Content/MainTemplate/img/favicon.ico" rel="icon">

<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Nunito:600,700" rel="stylesheet">

<!-- CSS Libraries -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/animate/animate.min.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/flaticon/font/flaticon.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Wano Quin:wght@900&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Blinker:wght@300;400;700&display=swap" />

<!-- Template Stylesheet -->
<link href="~/Content/bootstrap-5.3.3-dist/css/bootstrap.css" rel="stylesheet" />
<link href="~/Content/MainTemplate/css/style.css" rel="stylesheet">

@Html.Partial("_Loader")

<h5><a href="#" style="text-decoration:none" onclick="history.back()">Go back</a></h5>
<h2 style="margin:1.5rem 0 0">Checkout</h2>
@*<h6>ShopName + ShopLocation</h6>*@

<div class="container row">
    <div class="container border border-dark col-md-6" style="width: 48.5%; margin-left:0;">
        <h5 class="fw-bold" style="padding-top:0.5rem">Deliver To</h5>         
        <hr />
        <h6 class="fw-lighter">Delivery Arrival Time</h6>
        <div data-estArrivalTime-data="@estArrivalTime">@Html.Raw(estArrivalTime + " minutes")</div>
        <hr />
        <div class="row">
            <div class="col-md-6">
                <iframe width="200px"
                        height="200px"
                        style="border:0"
                        loading="lazy"
                        allowfullscreen
                        referrerpolicy="no-referrer-when-downgrade"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d171645.86751208323!2d-122.41941561052521!3d37.774929500000004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80859a6d00690021%3A0x4a501367f076adff!2sSpace%20Needle!5e0!3m2!1sen!2sus!4v1589983703817!5m2!1sen!2sus"></iframe>
            </div>
            <div class="col-md-6">
                <label>Address</label>
                <input type="text" name="address" required/>
                <label>Address Details</label>
                <input type="text" name="addressDetailsOrLandmark" />
                <label>Note to driver</label>
                <input type="text" name="noteToDriver" />
            </div>
        </div>

    </div>                                                                              
    <div class="container border border-dark col-md-6" style="width: 48.5%; margin-right:0;">
        <h5 class="fw-bold" style="padding-top:0.5rem">Order Summary</h5>
        <hr />

        <!--container for each shop-->
        <div>
            @*@foreach (var item in Model)
            {*@
                <div class="row" style="justify-content:center; align-items:center;">
                    <div class="col-md-1"><span>@Model.Qty</span>x</div>
                    <div class="col-md-2"><img src="@Url.Content(Model.ImagePath)" width="60px" height="60px" style="border-radius:50%;" /></div>
                    <div class="col-md-6">@Model.RecipeName</div>
                    <div class="col-md-3">&#8369; @Convert.ToDecimal(Model.Total_Price).ToString("0.00")</div>

                    @{ 
                        subTotal += Convert.ToDecimal(Model.Total_Price);
                    }
                </div>
            @*}*@
            @{
                total += (subTotal + deliveryFee);
            }
            <hr />
            <div class="row">
                <div class="col-md-12" style="display:flex; justify-content:space-between">
                    <div><h6>Subtotal</h6></div>
                    <div><h6>&#8369; @subTotal.ToString("0.00")</h6></div>
                </div>
                <div class="col-md-12" style="display:flex; justify-content:space-between">
                    <div>Delivery Fee</div>
                    
                    <div data-deliveryFee-data="@deliveryFee">&#8369; @deliveryFee</div>
                </div>
                @*<div class="col-md-12" style="display:flex; justify-content:space-between">
                    <div>Estimated arrival time</div>
                    <div data-estArrivalTime-data="@estArrivalTime">@Html.Raw(estArrivalTime + " minutes")</div>
                </div>*@
            </div>
        </div>    
        <!--outer loop-->                   
    </div>                                                                              
    <div class="container border border-dark col-md-6" style="width: 48.5%; margin-left:0; margin-top:0.85rem">
        <h5 class="fw-bold" style="padding-top:0.5rem">Payment Details</h5>
        <hr />
        <div class="row">
            <div class="col-md-12" style="margin-bottom:1rem">
                <div>
                    <label>Payment Method</label>
                </div>
                <div>
                    <select name="paymentMethod" style="width:100%">
                        <option value="gcash" disabled>Gcash</option>
                        <option value="visa" disabled>Visa</option>
                        <option value="paymaya" disabled>Paymaya</option>
                        <option value="cod" selected>Cash on Delivery</option>
                    </select>
                </div>

            </div>
            @*<div class="col-md-12" style="margin-bottom:1rem">
                <div>
                    <label>Profile</label>
                </div>
                <div>
                    <input type="text" name="profileInp" style="width:100%"/>
                </div>
            </div>*@
        </div>
    </div>
</div>

<div class="footer" style="display:flex; background:none !important; justify-content:space-evenly; align-items:center; gap:1rem; padding-bottom:2rem">
    <div>
        <p>Total</p>
        <h1>&#8369; @total.ToString("0.00")</h1>
    </div>
    <div>
        <button class="checkoutbtn" style="font-size: 1.5rem; width: 100%; height: 3rem; padding: 0 1.5rem !important; text-align: center;">Place Order</button>
    </div>
</div>



<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="~/Content/MainTemplate/lib/easing/easing.min.js"></script>
<script src="~/Content/MainTemplate/lib/owlcarousel/owl.carousel.min.js"></script>
<script src="~/Content/MainTemplate/lib/tempusdominus/js/moment.min.js"></script>
<script src="~/Content/MainTemplate/lib/tempusdominus/js/moment-timezone.min.js"></script>
<script src="~/Content/MainTemplate/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

<!-- Contact Javascript File -->
<script src="~/Content/MainTemplate/mail/jqBootstrapValidation.min.js"></script>
<script src="~/Content/MainTemplate/mail/contact.js"></script>

<!-- Template Javascript -->
<script src="~/Content/MainTemplate/js/main.js"></script>
<script src="~/Content/bootstrap-5.3.3-dist/js/bootstrap.js"></script>
<script src="~/Content/HideSomeeAds/removewatermark.js"></script>

<script>
    $(document).ready(function () {
        $('.checkoutbtn').click(function () {
            showLoader();

            var address = $('input[name="address"]').val();
            var paymentMethod = $('select[name="paymentMethod"]').val();
            var userId = @user.userID;
            var totalAmount = @total;
            var deliveryFee = @deliveryFee;
            var estArrivalTime = @estArrivalTime;
            //alert("fee: " + deliveryFee);
            //alert("estArrivalTime: " + estArrivalTime);
            $.ajax({
                type: 'POST',
                url: '@Url.Action("PlaceOrder", "UsersPage")',
                data: { id: userId, address: address, paymentMethod: paymentMethod, totalAmount: totalAmount, deliveryFee: deliveryFee, estArrivalTime: estArrivalTime},
                success: function (result) {
                    if (result.success) {
                        alert("Placed order successfully!");
                        window.location.href = '@Url.Action("UsersHome", "UsersPage")';
                    } else {
                        alert("Input all required fields (Address)");
                        window.location.href = '@Url.Action("CheckOutPage", "UsersPage")';
                    }
                },
                error: function (xhr, status, error) {
                    // Handle error
                    alert(error)
                },
                complete: function () {
                    hideLoader();
                }
            });
        });
    });
</script>

MoodBite/MoodBite/Views/UsersPage/ChooseMood.cshtml
@model IEnumerable<Mood>


@{
    ViewBag.Title = "Choose a mood";
    ViewBag.TitleHeader = "Select a mood first";
    ViewBag.TitleSubHeader = "Choose a mood";
    ViewBag.LoaderMsg = "Generating recommended recipes...";
    Layout = "~/Views/Shared/_StandardLayout.cshtml";
    User user = Session["User"] as User;
}

<!-- Favicon -->
<link href="~/Content/MainTemplate/img/favicon.ico" rel="icon">

<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Nunito:600,700" rel="stylesheet">

<!-- CSS Libraries -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/animate/animate.min.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/flaticon/font/flaticon.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

<!-- Template Stylesheet -->
<link href="~/Content/MainTemplate/css/style.css" rel="stylesheet">



<!-- Modal -->
<div class="modal chooseMoodModal" id="myModal" style="background-color:rgba(0,0,0,0.85);" onclick="handleModalClick(event)">
    <div class="modal-dialog">
        <div class="modal-content" data-backdrop="static" data-keyboard="false">
            <div class="modal-header">
                <h5 class="modal-title">Hi, @User.Identity.Name</h5>
            </div>
            @using (Html.BeginForm())
            {
                <div class="modal-body">
                    <div class="form-group">
                        <label for="moodSelect">How are you feeling today?</label>
                        <select class="form-control" id="moodSelect" name="chosenMood">
                            @foreach (var mood in Model)
                            {
                                <option value="@mood.MoodName">@mood.MoodName</option>
                            }
                        </select>
                    </div>
                </div>
                <div style="z-index:999">
                    @Html.Partial("_Loader")
                </div>
                <div class="modal-footer">
                    <button onclick="showLoader()" type="submit" class="btn btn-primary" id="selectMoodBtn">Next</button>
                </div>
            }
        </div>
    </div>
</div>



<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="~/Content/MainTemplate/lib/easing/easing.min.js"></script>
<script src="~/Content/MainTemplate/lib/owlcarousel/owl.carousel.min.js"></script>
<script src="~/Content/MainTemplate/lib/tempusdominus/js/moment.min.js"></script>
<script src="~/Content/MainTemplate/lib/tempusdominus/js/moment-timezone.min.js"></script>
<script src="~/Content/MainTemplate/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

<!-- Contact Javascript File -->
<script src="~/Content/MainTemplate/mail/jqBootstrapValidation.min.js"></script>
<script src="~/Content/MainTemplate/mail/contact.js"></script>

<!-- Template Javascript -->
<script src="~/Content/MainTemplate/js/main.js"></script>

<script src="~/Content/HideSomeeAds/removewatermark.js"></script>

<script>
    $(function() {
        // Get the modal element
        var modal = $('.chooseMoodModal');

        // Show the modal
        modal.modal('show');
    });

    function handleModalClick(event) {
        if (event.target === event.currentTarget || event.target.parentNode === event.currentTarget) {
             window.location.href = 'ChooseMood';
        }
    }
</script>