MoodBite/MoodBite/Models/ManageUploads/UpdateUploadsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MoodBite.Models.ManageUploads
{
    public class UpdateUploadsViewModel
    {
        public IEnumerable<RecipeIngredient> recipeIngredient;
        public Recipe recipe;
        public RecipeImage recipeImage;
    }
}

MoodBite/MoodBite/Models/RecipeViewModel/RecipeDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MoodBite.Models.RecipeViewModel
{
    public class RecipeDetailViewModel
    {
        public IEnumerable<vw_RecipeDetailsWithoutIngredients> recipeDetailsWithoutIngredients;
        public IEnumerable<vw_RecommendedRecipeForMood> recommendedRecipes;
        public Dictionary<string, List<string>> recipeIngredients;
        public IEnumerable<vw_CoverImageOfRecipes> imagesOfRecipe;
        public vw_CoverImageOfRecipes recipeImagesReadMore;
        public vw_RecommendedRecipeForMood recipeReadMore;
        public IEnumerable<RecipeIngredient> recipeIngredientsReadMore;
        public vw_RecipeDetailsWithoutIngredients recipeDetailsWithoutIngredientsReadMore;
        public IEnumerable<vw_RecipeDetailsWithoutIngredientsWithRating> recipeDetailsWithRating;
        public IEnumerable<vw_recipeUploadersNameWithRating> recipeUploadersNameWithRatingReadMore;
        public IEnumerable<vw_UsersUploadCounts> userUploadCounts;
        public vw_AllUserColWithRecipeID uploadersProfilePic;
        public IEnumerable<vw_AllRecipeDetailsWithFoodCategoryName> allRecipeWithFoodCategoryName;
        public IEnumerable<string> allergy;
        public IEnumerable<string> foodCategories;
        public IEnumerable<string> intolerance;
        public UserPremium userPremium;
        public vw_FoodSaleView foodSaleView;
        public IEnumerable<int> faveRecipes;
        public vw_RecipeReadMoreStocksView recipeStocksView;
        public List<vw_IncomingOrderView> incomingOrderView;
        public List<vw_MyFavoritesView> myFavoritesView;
    }
}

MoodBite/MoodBite/Controllers/AdminsPageController.cs
using MoodBite.Models.ManageUploads;
using MoodBite.Models.UserViewModel;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace MoodBite.Controllers
{
    [HandleError]
    [Authorize(Roles = "Admin")]
    [OutputCache(NoStore = true, Duration = 0)]
    public class AdminsPageController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Overview()
        {
            return View();
        }
        //Manage Users
        public ActionResult ManageUsers()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View(_db.vw_ManageUsers.ToList());
            }
            return RedirectToAction("../Account/Login");
        }
        public ActionResult ManageUploads()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View(_db.vw_ManageUploads.ToList());
            }
            return RedirectToAction("../Account/Login");
        }


        public ActionResult EditUser(int id)
        {
            if (User.Identity.IsAuthenticated)
            {
                var userView = new UserViewModel();
                userView.user = _db.User.Where(model => model.userID == id).FirstOrDefault();
                userView.userRole = _db.UserRole.Where(model => model.UserID == id).FirstOrDefault();
                userView.userRoleView = _db.vw_RoleView.Where(model => model.RoleID == userView.userRole.RoleID).FirstOrDefault();


                var user = _db.User.Where(model => model.userID == id).FirstOrDefault();
                Session["UserRole"] = _db.vw_RoleView.Where(model => model.RoleID == userView.userRole.RoleID).FirstOrDefault();
                
                return View(user);
            }
            return RedirectToAction("../Account/Login");
        }

        [HttpPost]
        public ActionResult EditUser(User u, HttpPostedFileBase profilePic, string pwdinp, string dob, string rolename)
        {
            if(Session["UserRole"] != null)
            {
                if (User.Identity.IsAuthenticated)
                {
                    try
                    {
                        int rolenameInt = Convert.ToInt32(rolename);

                        var userRoleSession = Session["UserRole"] as vw_RoleView;
                        var existingUser = _db.User.Where(model => model.userID == u.userID).FirstOrDefault();
                        var user = new User();
                        var userRole = new UserRole();

                        string[] dateInitInp = dob.Split('/');
                        string[] formatDateInitInp = new string[dateInitInp.Length];

                        formatDateInitInp[0] = dateInitInp[1];
                        formatDateInitInp[1] = dateInitInp[0];
                        formatDateInitInp[2] = dateInitInp[2];

                        string formattedDate = string.Join("-", formatDateInitInp);

                        DateTime dateOfBirthModel = new DateTime();

                        if (DateTime.TryParseExact(formattedDate, "dd-MM-yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out dateOfBirthModel))
                        {
                            user = u;
                            user.Email = existingUser.Email;
                            user.EmailConfirmationToken = existingUser.EmailConfirmationToken;
                            user.EmailConfirmed = existingUser.EmailConfirmed;
                            user.BirthDate = dateOfBirthModel;
                            if (profilePic != null)
                            {
                                if (profilePic != null && profilePic.ContentLength > 0)
                                {
                                    string fileName = Path.GetFileName(profilePic.FileName);
                                    string uniqueFileName = GetUniqueFileName("~/Content/UsersProfileImages/", fileName);
                                    string filePath = Path.Combine(Server.MapPath("~/Content/UsersProfileImages/"), uniqueFileName);

                                    profilePic.SaveAs(filePath);

                                    user.ProfilePicturePath = "~/Content/UsersProfileImages/" + uniqueFileName;
                                }
                                else
                                {
                                    return Json(new { success = false, message = "An error has occured" });
                                }
                            }
                            else
                            {
                                user.ProfilePicturePath = existingUser.ProfilePicturePath;
                            }
                            userRole = _db.UserRole.Where(model => model.UserID == u.userID).FirstOrDefault();
                            userRole.RoleID = rolenameInt;
                            _userRepo.Update(user.userID, user);
                            try
                            {
                                _userRoleRepo.Update(userRole.UserRoleID, userRole);

                                return Json(new { success = true, message = "Profile updated successfully" });
                            }
                            catch (Exception)
                            {
                                _userRepo.Delete(user.userID);
                                return Json(new { success = false, message = "An error has occured" });
                                throw;
                            }
                        }
                        else
                        {
                            return Json(new { success = false, message = "Invalid date format" });
                        }

                    }
                    catch (Exception)
                    {
                        return Json(new { success = false, message = "An error has occured." });
                    }
                }
                else
                {
                    return RedirectToAction("../Account/LogOut");
                }
            } else
            {
                return RedirectToAction("../Account/LogOut");
            }
        }

        public ActionResult ViewUserDetails(int id)
        {
            if (User.Identity.IsAuthenticated)
            {
                var userView = new UserViewModel();
                userView.user = _db.User.Where(model => model.userID == id).FirstOrDefault();
                userView.userRole = _db.UserRole.Where(model => model.UserID == id).FirstOrDefault();
                userView.userRoleView = _db.vw_RoleView.Where(model => model.RoleID == userView.userRole.RoleID).FirstOrDefault();
                userView.userPremium = _db.UserPremium.Where(model => model.UserID == userView.user.userID).FirstOrDefault();
                userView.userRecipe = _db.UserRecipe.Where(model => model.UserID == userView.user.userID).ToList();
                var userRecipe = _db.UserRecipe.Where(model => model.UserID == userView.user.userID).FirstOrDefault();


                if (userView.userPremium != null)
                {
                    userView.premiumType = _db.Premium.Where(model => model.PremiumID == userView.userPremium.PremiumID).FirstOrDefault();
                }
                else
                {
                    userView.premiumType = null;
                }

                if (userRecipe != null)
                {
                    userView.foodSale = _db.FoodSale.Where(model => model.UserRecipeID == userRecipe.UserRecipeID).ToList();

                } else
                {
                    userView.foodSale = null;
                }

                return View(userView);
            }
            return RedirectToAction("../Account/Login");
        }

        [HttpPost]
        public ActionResult DeleteUser(int id)
        {
            if (User.Identity.IsAuthenticated)
            {
                try
                {
                    _userRepo.Delete(id);
                    return Json(new { success = true});
                }
                catch (Exception)
                {
                    return Json(new { success = false });
                    throw;
                }
            } else
            {
                return RedirectToAction("../Account/LogOut");
            }
        }

        [HttpPost]
        public ActionResult ApproveRecipe(int id)
        {
            if (Session["User"] != null)
            {
                var adminInCharge = Session["User"] as User;
                var uploader = _db.UserRecipe.Where(model => model.RecipeID == id).FirstOrDefault();
                var uploaderUserProfile = _db.User.Where(model => model.userID == uploader.UserID).FirstOrDefault();
                var recipe = _db.Recipe.Where(model => model.RecipeID == id).FirstOrDefault();

                recipe.IsApproved = true;
                recipe.ApprovedBy = adminInCharge.userID;
                recipe.DateApproved = DateTime.Now;

                try
                {
                    _recipeRepo.Update(id, recipe);
                    string email = ConfigurationManager.AppSettings["Email"];
                    string password = "cmobmopkqmvqdriu";
                    string noreplyEmail = "no-reply@moodbite.com";

                    //string confirmationLink = Url.Action("ConfirmEmail", "Account", new { token = user.EmailConfirmationToken }, Request.Url.Scheme);

                    string subject = "Recipe Approval";

                    ////use this when deployed
                    //string body = $"Please confirm your email address by clicking <a href=\"{confirmationLink}\">here</a>";

MoodBite/MoodBite/Views/AdminsPage/Index.cshtml
@{
    ViewBag.Title = "Admins Dashboard";
    ViewBag.TitleHeader = "List of Users";
    ViewBag.SubHeader = "";
    ViewBag.LoaderMsg = "Please wait...";
    Layout = "~/Views/Shared/_StandardLayout.cshtml";

    string a = "active";
    string ia = string.Empty;

    Session["HomeActive"] = a;
    Session["MUploadsActive"] = ia;
    Session["MSubscriptionsActuve"] = ia;
}

<!-- Favicon -->
<link href="~/Content/MainTemplate/img/favicon.ico" rel="icon">

<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Nunito:600,700" rel="stylesheet">

<!-- CSS Libraries -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/animate/animate.min.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/flaticon/font/flaticon.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Wano Quin:wght@900&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Blinker:wght@300;400;700&display=swap" />

<!-- Template Stylesheet -->
<link href="~/Content/bootstrap-5.3.3-dist/css/bootstrap.css" rel="stylesheet" />
<link href="~/Content/MainTemplate/css/style.css" rel="stylesheet">


@Html.Partial("_Loader")

<div style="display:flex; flex-direction:row;">
    <div style="width:15%; margin-right:1rem;">
        <a href="@Url.Action("Overview", "AdminsPage")" class="admin-btns overview" style="color:white; text-decoration:none !important; width:100%;">
            <i class="fas fa-list"></i>
            <span class="my-cart-text" style="color:white">Overview</span>
        </a>
        <a href="@Url.Action("ManageUsers", "AdminsPage")" class="admin-btns manageusers" style="color:white; text-decoration:none !important; width:100%; ">
            <i class="fas fa-users"></i>
            <span class="my-cart-text" style="color:white">Manage Users</span>
        </a>

        <a href="@Url.Action("ManageUploads", "AdminsPage")" class="admin-btns manageuploads" style="color:white; text-decoration:none !important; width:100%;">
            <i class="fas fa-upload"></i>
            <span class="my-cart-text" style="color:white">Manage Uploads</span>
        </a>
    </div>

    <div style="width: 85%;" id="content">

    </div>
</div>

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="~/Content/MainTemplate/lib/easing/easing.min.js"></script>
<script src="~/Content/MainTemplate/lib/owlcarousel/owl.carousel.min.js"></script>
<script src="~/Content/MainTemplate/lib/tempusdominus/js/moment.min.js"></script>
<script src="~/Content/MainTemplate/lib/tempusdominus/js/moment-timezone.min.js"></script>
<script src="~/Content/MainTemplate/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

<!-- Contact Javascript File -->
<script src="~/Content/MainTemplate/mail/jqBootstrapValidation.min.js"></script>
<script src="~/Content/MainTemplate/mail/contact.js"></script>

<!-- Template Javascript -->
<script src="~/Content/MainTemplate/js/main.js"></script>
<script src="~/Content/bootstrap-5.3.3-dist/js/bootstrap.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.0.5/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.0.5/js/dataTables.bootstrap5.js"></script>

<script src="~/Content/HideSomeeAds/removewatermark.js"></script>
<script>
    $(document).ready(function () {
        function loadPartialView(url) {
            $.get(url, function (data) {
                $('#content').html(data);
            });
        }

        // Load Manage Users view by default
        loadPartialView('@Url.Action("ManageUsers", "AdminsPage")');

        // Click event handlers for navigation
        $('.admin-btns').click(function (e) {
            e.preventDefault();
            showLoader();
            var url = $(this).attr('href');
            loadPartialView(url);
            hideLoader();
        });
    });

    //$(document).ready(function () {
    //    // Initialize DataTable
    //    $('#manageuserstable').DataTable();
    //    console.log("Index");
    //});
</script>

MoodBite/MoodBite/Views/AdminsPage/ManageUploads.cshtml
@model IEnumerable<MoodBite.vw_ManageUploads>

@{
    ViewBag.Title = "Manage Uploads";
    ViewBag.TitleHeader = "List of Uploaded Recipes";
    ViewBag.SubHeader = "";
    ViewBag.LoaderMsg = "Please wait...";
    string a = "active";
    string ia = string.Empty;

    Session["HomeActive"] = ia;
    Session["MUploadsActive"] = a;
    Session["MSubscriptionsActuve"] = ia;
}

@*<!-- Favicon -->
<link href="~/Content/MainTemplate/img/favicon.ico" rel="icon">

<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Nunito:600,700" rel="stylesheet">

<!-- CSS Libraries -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/animate/animate.min.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/flaticon/font/flaticon.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Wano Quin:wght@900&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Blinker:wght@300;400;700&display=swap" />

<!-- Template Stylesheet -->
<link href="~/Content/bootstrap-5.3.3-dist/css/bootstrap.css" rel="stylesheet" />
<link href="~/Content/MainTemplate/css/style.css" rel="stylesheet">*@

@Html.Partial("_Loader")

<table id="manageuploadstable" class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Recipe name")
            </th>
            <th>
                @Html.DisplayName("Uploaded by")
            </th>
            <th>
                @Html.DisplayName("Date uploaded")
            </th>
            <th>
                @Html.DisplayName("Status")
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr data-id="@item.ID">
                <td>
                    @Html.DisplayFor(modelItem => item.RecipeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Uploaded_by)
                </td>
                <td>
                    @if (item.Date_uploaded.HasValue)
                    {
                        <span>@item.Date_uploaded.Value.ToString("MMMM dd, yyyy hh:mm tt")</span>
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status, new { @class = "status" })
                </td>
                <td>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="actionsDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Actions
                        </button>
                        <div class="dropdown-menu" aria-labelledby="actionsDropdown">
                            <a class="dropdown-item" onclick="showLoader()" href="~/AdminsPage/EditRecipe/@item.ID">Edit</a>
                            <a class="dropdown-item" onclick="showLoader()" href="~/AdminsPage/RecipeDetails/@item.ID">Details</a>
                            @if (item.DateApproved == null || (item.DateApproved != null && item.Status == "Rejected"))
                            {
                                <a class="dropdown-item" onclick="showLoader()" href="~/AdminsPage/DeleteRecipe/@item.ID">Delete</a>
                                <a class="dropdown-item" href="#" onclick="approveRecipe(@item.ID)">Approve</a>
                                <a class="dropdown-item" href="#" onclick="rejectRecipe(@item.ID)">Reject</a>
                                //~/ AdminsPage / RejectRecipe / @item.ID
                            }
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>




@*<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="~/Content/MainTemplate/lib/easing/easing.min.js"></script>
<script src="~/Content/MainTemplate/lib/owlcarousel/owl.carousel.min.js"></script>
<script src="~/Content/MainTemplate/lib/tempusdominus/js/moment.min.js"></script>
<script src="~/Content/MainTemplate/lib/tempusdominus/js/moment-timezone.min.js"></script>
<script src="~/Content/MainTemplate/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

<!-- Contact Javascript File -->
<script src="~/Content/MainTemplate/mail/jqBootstrapValidation.min.js"></script>
<script src="~/Content/MainTemplate/mail/contact.js"></script>

<!-- Template Javascript -->
<script src="~/Content/MainTemplate/js/main.js"></script>
<script src="~/Content/bootstrap-5.3.3-dist/js/bootstrap.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.0.5/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.0.5/js/dataTables.bootstrap5.js"></script>*@

<script>

    $(document).ready(function () {
        $('#statusDropdown').change(function () {
            var selectedValue = $(this).val();
            var itemId = $(this).data('id');

            $.ajax({
                url: '@Url.Action("UpdateRecipeStatus", "AdminsPage")',
                type: 'POST',
                data: { id: itemId, status: selectedValue },
                success: function (result) {
                    console.log(result);
                },
                error: function (xhr, status, error) {
                    console.log(error);
                }
            });
        });
    });

    function approveRecipe(id) {
        $('#loadertxt').text('Approving...');
        showLoader();
        $.ajax({
            url: '/AdminsPage/ApproveRecipe/' + id,
            type: 'POST',
            success: function (response) {
                if (response.success) {
                    alert('Recipe approved successfully!');

                    var row = $('#manageuploadstable').find('tr[data-id="' + id + '"]');
                    row.find('.status').text('Approved');
                } else {
                    alert('Failed to approve recipe.');
                }
            },
            error: function () {
                alert('An error occurred.');
            },
            complete: function () {
                hideLoader();
            }
        });
    }
    function rejectRecipe(id) {
        $('#loadertxt').text('Rejecting...');
        showLoader();
        $.ajax({
            url: '/AdminsPage/RejectRecipe/' + id,
            type: 'POST',
            success: function (response) {
                if (response.success) {
                    alert('Recipe rejected successfully!');

                    var row = $('#manageuploadstable').find('tr[data-id="' + id + '"]');
                    row.find('.status').text('Rejected');
                } else {
                    alert('Failed to reject recipe.');
                }
            },
            error: function () {
                alert('An error occurred.');
            },
            complete: function () {
                hideLoader();
            }
        });
    }

    $(document).ready(function () {
        // Initialize DataTable
        $('#manageuploadstable').DataTable();
    });
</script>

MoodBite/MoodBite/Views/AdminsPage/ManageUsers.cshtml
@model IEnumerable<MoodBite.vw_ManageUsers>

@{
    ViewBag.Title = "Manage Users";
    ViewBag.TitleHeader = "List of Users";
    ViewBag.SubHeader = "";

    string a = "active";
    string ia = string.Empty;

    Session["HomeActive"] = a;
    Session["MUploadsActive"] = ia;
    Session["MSubscriptionsActuve"] = ia;
}

@*<!-- Favicon -->
<link href="~/Content/MainTemplate/img/favicon.ico" rel="icon">

<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Nunito:600,700" rel="stylesheet">

<!-- CSS Libraries -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/animate/animate.min.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/flaticon/font/flaticon.css" rel="stylesheet">
<link href="~/Content/MainTemplate/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Wano Quin:wght@900&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Blinker:wght@300;400;700&display=swap" />

<!-- Template Stylesheet -->
<link href="~/Content/bootstrap-5.3.3-dist/css/bootstrap.css" rel="stylesheet" />
<link href="~/Content/MainTemplate/css/style.css" rel="stylesheet">*@

@*<div style="text-align: right; margin:1rem 0 0.5rem">
    <a href="~/AdminsPage/AddUser" class="btn custom-btn" style="padding: 5px 10px;">Add new</a>
</div>*@

@Html.Partial("_Loader")
  
<table id="manageuserstable" class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Username")
            </th>
            <th>
                @Html.DisplayName("First name")
            </th>
            <th>
                @Html.DisplayName("Last name")
            </th>
            <th>
                @Html.DisplayName("Role")
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Username)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.First_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Last_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Role)
                </td>
                <td>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="actionsDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Actions
                        </button>
                        <div class="dropdown-menu" aria-labelledby="actionsDropdown">
                            <a class="dropdown-item" href="#" onclick="editUser(@item.ID)">Edit</a>
                            <a class="dropdown-item" href="#" onclick="viewUserDetails(@item.ID)">Details</a>
                            <a class="dropdown-item" href="#" onclick="deleteUser(@item.ID)">Delete</a>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>


@*<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="~/Content/MainTemplate/lib/easing/easing.min.js"></script>
<script src="~/Content/MainTemplate/lib/owlcarousel/owl.carousel.min.js"></script>
<script src="~/Content/MainTemplate/lib/tempusdominus/js/moment.min.js"></script>
<script src="~/Content/MainTemplate/lib/tempusdominus/js/moment-timezone.min.js"></script>
<script src="~/Content/MainTemplate/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

<!-- Contact Javascript File -->
<script src="~/Content/MainTemplate/mail/jqBootstrapValidation.min.js"></script>
<script src="~/Content/MainTemplate/mail/contact.js"></script>

<!-- Template Javascript -->
<script src="~/Content/MainTemplate/js/main.js"></script>
<script src="~/Content/bootstrap-5.3.3-dist/js/bootstrap.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.0.5/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.0.5/js/dataTables.bootstrap5.js"></script>*@

<script>
    $(document).ready(function () {
        // Initialize DataTable
        $('#manageuserstable').DataTable();
    });

    function editUser(id) {
        showLoader();
        window.location.href = `/AdminsPage/EditUser/${id}`;
        //hideLoader();
    }

    function viewUserDetails(id) {
        showLoader();
        window.location.href = `/AdminsPage/ViewUserDetails/${id}`;
        //hideLoader();
    }

    function deleteUser(id) {
        /*
        if yes then do this (showLoader();
        window.location.href = `/AdminsPage/DeleteUser/${id}`;)
        otherwise just do nothing
        */
        if(confirm("Are you sure you want to delete this user?")){
            showLoader();
            $.ajax({
                url: '/AdminsPage/DeleteUser/' + id,
                type: 'POST',
                success: function (response) {
                    if (response.success) {
                        alert('User deleted successfully!');
                        window.location.reload();
                    } else {
                        alert('Failed to delete user.');
                        window.location.reload();
                    }
                },
                error: function () {
                    alert('An error occurred.');
                },
                complete: function () {
                    hideLoader();
                }
            });
        }
        //hideLoader();
    }
</script>